title: Atomic Slider
status: 'wip'
preview: '@preview'
context:
  slider:
    items:
      - '<img src="https://placehold.it/1000x500"/>'
      - '<img src="https://placehold.it/1000x500"/>'
      - '<img src="https://placehold.it/1000x500"/>'
      - '<img src="https://placehold.it/1000x500"/>'
      - '<img src="https://placehold.it/1000x500"/>'
      - '<img src="https://placehold.it/1000x500"/>'
variants:
  - name: 'Progress'
    context:
      slider:
        options:
          autoplay: true,
          rewind: true
        modifiers:
          - 'has-dots-progress'
